#!/bin/bash
set -euo pipefail

# Arguments
MODE="${1:-simple}"
CLUSTER_SIZE="${2:?Cluster size not provided}"
MEMORY_PER_MACHINE_GB="${3:?Memory per machine not provided}"
EPC_PER_MACHINE_GB="${4:?EPC per machine not provided}"
NUM_MACHINES="${5:?Number of machines not provided}"

# Constants
RESERVED_FOR_MASTER_GB=2
DEFAULT_WORKER_CORES=2
MEMORY_OVERHEAD_FACTOR=0.10
MIN_EXECUTOR_MEMORY_GB=1

# Calculate memory and EPC
TOTAL_MEMORY=$(( MEMORY_PER_MACHINE_GB * NUM_MACHINES - RESERVED_FOR_MASTER_GB ))
TOTAL_EPC=$(( EPC_PER_MACHINE_GB * NUM_MACHINES ))

MEMORY_PER_WORKER=$(( TOTAL_MEMORY / CLUSTER_SIZE ))
EPC_PER_WORKER=$(( TOTAL_EPC / CLUSTER_SIZE ))

if [[ "$MODE" == "simple" ]]; then
  if (( EPC_PER_WORKER > 1 )); then
    EXECUTOR_MEMORY_GB=$(( EPC_PER_WORKER - 1 ))
  else
    EXECUTOR_MEMORY_GB=1
  fi

  WORKER_MEMORY_GB=$(( EXECUTOR_MEMORY_GB + 1 ))
  WORKER_CORES="$DEFAULT_WORKER_CORES"
  DRIVER_MEMORY_GB=4
  DRIVER_MEMORY_OVERHEAD_GB=1

  echo "SPARK_EXECUTOR_MEMORY_GB=$EXECUTOR_MEMORY_GB"
  echo "SPARK_WORKER_MEMORY_GB=$WORKER_MEMORY_GB"
  echo "SPARK_WORKER_CORES=$WORKER_CORES"
  echo "SPARK_DRIVER_MEMORY_GB=$DRIVER_MEMORY_GB"
  echo "SPARK_DRIVER_MEMORY_OVERHEAD_GB=$DRIVER_MEMORY_OVERHEAD_GB"
  echo "SPARK_DAEMON_MEMORY=\"${DRIVER_MEMORY_GB}g\""
  echo "SPARK_GC_OPTS=\"-XX:+UseParallelGC -XX:+UseParallelOldGC\""

elif [[ "$MODE" == "optimal" ]]; then
  if (( CLUSTER_SIZE <= 10 )); then
    TARGET_EXECUTOR_MEMORY_GB=6
  elif (( CLUSTER_SIZE <= 50 )); then
    TARGET_EXECUTOR_MEMORY_GB=12
  else
    TARGET_EXECUTOR_MEMORY_GB=24
  fi

  MAX_EXECUTOR_MEMORY_GB=$(awk "BEGIN { printf \"%.0f\", ${EPC_PER_WORKER} / (1 + ${MEMORY_OVERHEAD_FACTOR}) }")

  if (( TARGET_EXECUTOR_MEMORY_GB > MAX_EXECUTOR_MEMORY_GB )); then
    EXECUTOR_MEMORY_GB="$MAX_EXECUTOR_MEMORY_GB"
  else
    EXECUTOR_MEMORY_GB="$TARGET_EXECUTOR_MEMORY_GB"
  fi

  if (( EXECUTOR_MEMORY_GB < MIN_EXECUTOR_MEMORY_GB )); then
    echo "⚠️ Warning: Executor memory ${EXECUTOR_MEMORY_GB}GB is less than recommended minimum (${MIN_EXECUTOR_MEMORY_GB}GB)." >&2
    EXECUTOR_MEMORY_GB=$MIN_EXECUTOR_MEMORY_GB
  fi

  MEMORY_OVERHEAD_GB=$(awk "BEGIN { printf \"%.0f\", ${EXECUTOR_MEMORY_GB} * ${MEMORY_OVERHEAD_FACTOR} }")
  TOTAL_EXECUTOR_MEMORY_GB=$(( EXECUTOR_MEMORY_GB + MEMORY_OVERHEAD_GB ))

  WORKER_MEMORY_GB="$TOTAL_EXECUTOR_MEMORY_GB"
  WORKER_CORES="$DEFAULT_WORKER_CORES"

  if (( CLUSTER_SIZE <= 10 )); then
    DRIVER_MEMORY_GB=4
  elif (( CLUSTER_SIZE <= 50 )); then
    DRIVER_MEMORY_GB=8
  else
    DRIVER_MEMORY_GB=12
  fi

  DRIVER_MEMORY_OVERHEAD_GB=$(awk "BEGIN { printf \"%.0f\", ${DRIVER_MEMORY_GB} * ${MEMORY_OVERHEAD_FACTOR} }")

  echo "SPARK_EXECUTOR_MEMORY_GB=$EXECUTOR_MEMORY_GB"
  echo "SPARK_EXECUTOR_MEMORY_OVERHEAD_GB=$MEMORY_OVERHEAD_GB"
  echo "SPARK_WORKER_MEMORY_GB=$WORKER_MEMORY_GB"
  echo "SPARK_WORKER_CORES=$WORKER_CORES"
  echo "SPARK_DRIVER_MEMORY_GB=$DRIVER_MEMORY_GB"
  echo "SPARK_DRIVER_MEMORY_OVERHEAD_GB=$DRIVER_MEMORY_OVERHEAD_GB"
  echo "SPARK_DAEMON_MEMORY=\"${DRIVER_MEMORY_GB}g\""
  echo "SPARK_GC_OPTS=\"-XX:+UseParallelGC -XX:+UseParallelOldGC\""

else
  echo "❌ Unknown mode: $MODE (use simple or optimal)" >&2
  exit 1
fi

